import mongoose from "mongoose";
import dotenv from "dotenv";
import Question from "../models/question.model.js";
dotenv.config();

mongoose.connect(process.env.MONGODB_URL)
  .then(() => console.log("Connected to MongoDB"))
  .catch(err => { console.error(err); process.exit(1); });

const s = (js, py, java, cpp) => ({ javascript: js, python: py, java, cpp });

const google = [
  { title:"Two Sum", difficulty:"Easy", description:"Given an array of integers and a target, return indices of the two numbers that add up to target.", snippets: s("function twoSum(nums,target){\n  \n}","def twoSum(nums,target):\n    pass","class Solution{\n  public int[] twoSum(int[] nums,int target){\n  }\n}","class Solution{\npublic:\n  vector<int> twoSum(vector<int>&nums,int target){\n  }\n};")},
  { title:"Longest Substring Without Repeating Characters", difficulty:"Medium", description:"Find the length of the longest substring without repeating characters.", snippets: s("function lengthOfLongestSubstring(s){\n  \n}","def lengthOfLongestSubstring(s):\n    pass","class Solution{\n  public int lengthOfLongestSubstring(String s){\n  }\n}","class Solution{\npublic:\n  int lengthOfLongestSubstring(string s){\n  }\n};")},
  { title:"Median of Two Sorted Arrays", difficulty:"Hard", description:"Find the median of two sorted arrays in O(log(m+n)) time.", snippets: s("function findMedianSortedArrays(nums1,nums2){\n  \n}","def findMedianSortedArrays(nums1,nums2):\n    pass","class Solution{\n  public double findMedianSortedArrays(int[] nums1,int[] nums2){\n  }\n}","class Solution{\npublic:\n  double findMedianSortedArrays(vector<int>&nums1,vector<int>&nums2){\n  }\n};")},
  { title:"Merge Intervals", difficulty:"Medium", description:"Given an array of intervals, merge all overlapping intervals.", snippets: s("function merge(intervals){\n  \n}","def merge(intervals):\n    pass","class Solution{\n  public int[][] merge(int[][] intervals){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> merge(vector<vector<int>>&intervals){\n  }\n};")},
  { title:"Jump Game", difficulty:"Medium", description:"Given an array of non-negative integers, determine if you can reach the last index.", snippets: s("function canJump(nums){\n  \n}","def canJump(nums):\n    pass","class Solution{\n  public boolean canJump(int[] nums){\n  }\n}","class Solution{\npublic:\n  bool canJump(vector<int>&nums){\n  }\n};")},
  { title:"Jump Game II", difficulty:"Medium", description:"Find the minimum number of jumps to reach the last index.", snippets: s("function jump(nums){\n  \n}","def jump(nums):\n    pass","class Solution{\n  public int jump(int[] nums){\n  }\n}","class Solution{\npublic:\n  int jump(vector<int>&nums){\n  }\n};")},
  { title:"Maximum Subarray", difficulty:"Medium", description:"Find the contiguous subarray which has the largest sum (Kadane's Algorithm).", snippets: s("function maxSubArray(nums){\n  \n}","def maxSubArray(nums):\n    pass","class Solution{\n  public int maxSubArray(int[] nums){\n  }\n}","class Solution{\npublic:\n  int maxSubArray(vector<int>&nums){\n  }\n};")},
  { title:"Search in Rotated Sorted Array", difficulty:"Medium", description:"Search for a target in a rotated sorted array in O(log n).", snippets: s("function search(nums,target){\n  \n}","def search(nums,target):\n    pass","class Solution{\n  public int search(int[] nums,int target){\n  }\n}","class Solution{\npublic:\n  int search(vector<int>&nums,int target){\n  }\n};")},
  { title:"Trapping Rain Water", difficulty:"Hard", description:"Given an elevation map, compute how much water it can trap after raining.", snippets: s("function trap(height){\n  \n}","def trap(height):\n    pass","class Solution{\n  public int trap(int[] height){\n  }\n}","class Solution{\npublic:\n  int trap(vector<int>&height){\n  }\n};")},
  { title:"Container With Most Water", difficulty:"Medium", description:"Find two lines that together with the x-axis forms a container that holds the most water.", snippets: s("function maxArea(height){\n  \n}","def maxArea(height):\n    pass","class Solution{\n  public int maxArea(int[] height){\n  }\n}","class Solution{\npublic:\n  int maxArea(vector<int>&height){\n  }\n};")},
  { title:"3Sum", difficulty:"Medium", description:"Find all unique triplets in the array which gives the sum of zero.", snippets: s("function threeSum(nums){\n  \n}","def threeSum(nums):\n    pass","class Solution{\n  public List<List<Integer>> threeSum(int[] nums){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> threeSum(vector<int>&nums){\n  }\n};")},
  { title:"4Sum", difficulty:"Medium", description:"Find all unique quadruplets that sum to the target.", snippets: s("function fourSum(nums,target){\n  \n}","def fourSum(nums,target):\n    pass","class Solution{\n  public List<List<Integer>> fourSum(int[] nums,int target){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> fourSum(vector<int>&nums,int target){\n  }\n};")},
  { title:"Rotate Array", difficulty:"Medium", description:"Rotate an array to the right by k steps.", snippets: s("function rotate(nums,k){\n  \n}","def rotate(nums,k):\n    pass","class Solution{\n  public void rotate(int[] nums,int k){\n  }\n}","class Solution{\npublic:\n  void rotate(vector<int>&nums,int k){\n  }\n};")},
  { title:"Best Time to Buy and Sell Stock", difficulty:"Easy", description:"Find the maximum profit from a single buy and sell transaction.", snippets: s("function maxProfit(prices){\n  \n}","def maxProfit(prices):\n    pass","class Solution{\n  public int maxProfit(int[] prices){\n  }\n}","class Solution{\npublic:\n  int maxProfit(vector<int>&prices){\n  }\n};")},
  { title:"Best Time to Buy and Sell Stock II", difficulty:"Medium", description:"Maximize profit with as many transactions as you like.", snippets: s("function maxProfit(prices){\n  \n}","def maxProfit(prices):\n    pass","class Solution{\n  public int maxProfit(int[] prices){\n  }\n}","class Solution{\npublic:\n  int maxProfit(vector<int>&prices){\n  }\n};")},
  { title:"Spiral Matrix", difficulty:"Medium", description:"Return all elements of the matrix in spiral order.", snippets: s("function spiralOrder(matrix){\n  \n}","def spiralOrder(matrix):\n    pass","class Solution{\n  public List<Integer> spiralOrder(int[][] matrix){\n  }\n}","class Solution{\npublic:\n  vector<int> spiralOrder(vector<vector<int>>&matrix){\n  }\n};")},
  { title:"Set Matrix Zeroes", difficulty:"Medium", description:"If an element is 0, set its entire row and column to 0.", snippets: s("function setZeroes(matrix){\n  \n}","def setZeroes(matrix):\n    pass","class Solution{\n  public void setZeroes(int[][] matrix){\n  }\n}","class Solution{\npublic:\n  void setZeroes(vector<vector<int>>&matrix){\n  }\n};")},
  { title:"Subsets", difficulty:"Medium", description:"Return all possible subsets of an integer array.", snippets: s("function subsets(nums){\n  \n}","def subsets(nums):\n    pass","class Solution{\n  public List<List<Integer>> subsets(int[] nums){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> subsets(vector<int>&nums){\n  }\n};")},
  { title:"Permutations", difficulty:"Medium", description:"Return all possible permutations of an array of distinct integers.", snippets: s("function permute(nums){\n  \n}","def permute(nums):\n    pass","class Solution{\n  public List<List<Integer>> permute(int[] nums){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> permute(vector<int>&nums){\n  }\n};")},
  { title:"Combination Sum", difficulty:"Medium", description:"Find all combinations that sum to target using elements from candidates.", snippets: s("function combinationSum(candidates,target){\n  \n}","def combinationSum(candidates,target):\n    pass","class Solution{\n  public List<List<Integer>> combinationSum(int[] candidates,int target){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> combinationSum(vector<int>&candidates,int target){\n  }\n};")},
  { title:"Letter Combinations of a Phone Number", difficulty:"Medium", description:"Return all possible letter combinations for a digit string.", snippets: s("function letterCombinations(digits){\n  \n}","def letterCombinations(digits):\n    pass","class Solution{\n  public List<String> letterCombinations(String digits){\n  }\n}","class Solution{\npublic:\n  vector<string> letterCombinations(string digits){\n  }\n};")},
  { title:"Valid Parentheses", difficulty:"Easy", description:"Determine if an input string of brackets is valid.", snippets: s("function isValid(s){\n  \n}","def isValid(s):\n    pass","class Solution{\n  public boolean isValid(String s){\n  }\n}","class Solution{\npublic:\n  bool isValid(string s){\n  }\n};")},
  { title:"Generate Parentheses", difficulty:"Medium", description:"Generate all combinations of well-formed parentheses for n pairs.", snippets: s("function generateParenthesis(n){\n  \n}","def generateParenthesis(n):\n    pass","class Solution{\n  public List<String> generateParenthesis(int n){\n  }\n}","class Solution{\npublic:\n  vector<string> generateParenthesis(int n){\n  }\n};")},
  { title:"Longest Common Prefix", difficulty:"Easy", description:"Find the longest common prefix string among an array of strings.", snippets: s("function longestCommonPrefix(strs){\n  \n}","def longestCommonPrefix(strs):\n    pass","class Solution{\n  public String longestCommonPrefix(String[] strs){\n  }\n}","class Solution{\npublic:\n  string longestCommonPrefix(vector<string>&strs){\n  }\n};")},
  { title:"Climbing Stairs", difficulty:"Easy", description:"Count distinct ways to climb n stairs taking 1 or 2 steps at a time.", snippets: s("function climbStairs(n){\n  \n}","def climbStairs(n):\n    pass","class Solution{\n  public int climbStairs(int n){\n  }\n}","class Solution{\npublic:\n  int climbStairs(int n){\n  }\n};")},
  { title:"Coin Change", difficulty:"Medium", description:"Find the fewest coins needed to make up the given amount.", snippets: s("function coinChange(coins,amount){\n  \n}","def coinChange(coins,amount):\n    pass","class Solution{\n  public int coinChange(int[] coins,int amount){\n  }\n}","class Solution{\npublic:\n  int coinChange(vector<int>&coins,int amount){\n  }\n};")},
  { title:"Longest Increasing Subsequence", difficulty:"Medium", description:"Find the length of the longest strictly increasing subsequence.", snippets: s("function lengthOfLIS(nums){\n  \n}","def lengthOfLIS(nums):\n    pass","class Solution{\n  public int lengthOfLIS(int[] nums){\n  }\n}","class Solution{\npublic:\n  int lengthOfLIS(vector<int>&nums){\n  }\n};")},
  { title:"Word Break", difficulty:"Medium", description:"Determine if string s can be segmented into words from the dictionary.", snippets: s("function wordBreak(s,wordDict){\n  \n}","def wordBreak(s,wordDict):\n    pass","class Solution{\n  public boolean wordBreak(String s,List<String> wordDict){\n  }\n}","class Solution{\npublic:\n  bool wordBreak(string s,vector<string>&wordDict){\n  }\n};")},
  { title:"House Robber", difficulty:"Medium", description:"Rob houses without alerting police (no two adjacent houses).", snippets: s("function rob(nums){\n  \n}","def rob(nums):\n    pass","class Solution{\n  public int rob(int[] nums){\n  }\n}","class Solution{\npublic:\n  int rob(vector<int>&nums){\n  }\n};")},
  { title:"Decode Ways", difficulty:"Medium", description:"Count the number of ways to decode an encoded message string.", snippets: s("function numDecodings(s){\n  \n}","def numDecodings(s):\n    pass","class Solution{\n  public int numDecodings(String s){\n  }\n}","class Solution{\npublic:\n  int numDecodings(string s){\n  }\n};")},
].map(q => ({...q, company:'google'}));

const amazon = [
  { title:"Number of Islands", difficulty:"Medium", description:"Count islands in a 2D grid using DFS/BFS.", snippets: s("function numIslands(grid){\n  \n}","def numIslands(grid):\n    pass","class Solution{\n  public int numIslands(char[][] grid){\n  }\n}","class Solution{\npublic:\n  int numIslands(vector<vector<char>>&grid){\n  }\n};")},
  { title:"LRU Cache", difficulty:"Medium", description:"Design an LRU Cache with O(1) get and put operations.", snippets: s("class LRUCache{\n  constructor(capacity){\n  }\n  get(key){}\n  put(key,val){}\n}","class LRUCache:\n  def __init__(self,cap):\n      pass\n  def get(self,key):pass\n  def put(self,key,val):pass","class LRUCache{\n  public LRUCache(int capacity){}\n  public int get(int key){}\n  public void put(int key,int value){}\n}","class LRUCache{\npublic:\n  LRUCache(int cap){}\n  int get(int key){}\n  void put(int key,int val){}\n};")},
  { title:"Word Ladder", difficulty:"Hard", description:"Find the shortest transformation sequence from beginWord to endWord.", snippets: s("function ladderLength(begin,end,list){\n  \n}","def ladderLength(begin,end,lst):\n    pass","class Solution{\n  public int ladderLength(String b,String e,List<String> l){\n  }\n}","class Solution{\npublic:\n  int ladderLength(string b,string e,vector<string>&l){\n  }\n};")},
  { title:"Reorder Log Files", difficulty:"Easy", description:"Reorder log files: letter logs before digit logs, letter logs sorted.", snippets: s("function reorderLogFiles(logs){\n  \n}","def reorderLogFiles(logs):\n    pass","class Solution{\n  public String[] reorderLogFiles(String[] logs){\n  }\n}","class Solution{\npublic:\n  vector<string> reorderLogFiles(vector<string>&logs){\n  }\n};")},
  { title:"Top K Frequent Elements", difficulty:"Medium", description:"Return the k most frequent elements from an integer array.", snippets: s("function topKFrequent(nums,k){\n  \n}","def topKFrequent(nums,k):\n    pass","class Solution{\n  public int[] topKFrequent(int[] nums,int k){\n  }\n}","class Solution{\npublic:\n  vector<int> topKFrequent(vector<int>&nums,int k){\n  }\n};")},
  { title:"K Closest Points to Origin", difficulty:"Medium", description:"Return the k closest points to the origin (0,0).", snippets: s("function kClosest(points,k){\n  \n}","def kClosest(points,k):\n    pass","class Solution{\n  public int[][] kClosest(int[][] points,int k){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> kClosest(vector<vector<int>>&points,int k){\n  }\n};")},
  { title:"Minimum Cost to Connect Sticks", difficulty:"Medium", description:"Find the minimum cost to connect all sticks using a priority queue.", snippets: s("function connectSticks(sticks){\n  \n}","def connectSticks(sticks):\n    pass","class Solution{\n  public int connectSticks(int[] sticks){\n  }\n}","class Solution{\npublic:\n  int connectSticks(vector<int>&sticks){\n  }\n};")},
  { title:"Two Sum II - Input Array Is Sorted", difficulty:"Medium", description:"Find two numbers in sorted array that add up to target (1-indexed).", snippets: s("function twoSum(numbers,target){\n  \n}","def twoSum(numbers,target):\n    pass","class Solution{\n  public int[] twoSum(int[] numbers,int target){\n  }\n}","class Solution{\npublic:\n  vector<int> twoSum(vector<int>&numbers,int target){\n  }\n};")},
  { title:"Palindrome Linked List", difficulty:"Easy", description:"Determine if a linked list is a palindrome.", snippets: s("function isPalindrome(head){\n  \n}","def isPalindrome(head):\n    pass","class Solution{\n  public boolean isPalindrome(ListNode head){\n  }\n}","class Solution{\npublic:\n  bool isPalindrome(ListNode* head){\n  }\n};")},
  { title:"Merge Two Sorted Lists", difficulty:"Easy", description:"Merge two sorted linked lists and return the merged list.", snippets: s("function mergeTwoLists(l1,l2){\n  \n}","def mergeTwoLists(l1,l2):\n    pass","class Solution{\n  public ListNode mergeTwoLists(ListNode l1,ListNode l2){\n  }\n}","class Solution{\npublic:\n  ListNode* mergeTwoLists(ListNode* l1,ListNode* l2){\n  }\n};")},
  { title:"Reverse Linked List", difficulty:"Easy", description:"Reverse a singly linked list.", snippets: s("function reverseList(head){\n  \n}","def reverseList(head):\n    pass","class Solution{\n  public ListNode reverseList(ListNode head){\n  }\n}","class Solution{\npublic:\n  ListNode* reverseList(ListNode* head){\n  }\n};")},
  { title:"Detect Cycle in Linked List", difficulty:"Easy", description:"Determine if a linked list has a cycle using Floyd's algorithm.", snippets: s("function hasCycle(head){\n  \n}","def hasCycle(head):\n    pass","class Solution{\n  public boolean hasCycle(ListNode head){\n  }\n}","class Solution{\npublic:\n  bool hasCycle(ListNode* head){\n  }\n};")},
  { title:"Minimum Window Substring", difficulty:"Hard", description:"Find the minimum window in s containing all characters of t.", snippets: s("function minWindow(s,t){\n  \n}","def minWindow(s,t):\n    pass","class Solution{\n  public String minWindow(String s,String t){\n  }\n}","class Solution{\npublic:\n  string minWindow(string s,string t){\n  }\n};")},
  { title:"Sliding Window Maximum", difficulty:"Hard", description:"Return max values from each window of size k using deque.", snippets: s("function maxSlidingWindow(nums,k){\n  \n}","def maxSlidingWindow(nums,k):\n    pass","class Solution{\n  public int[] maxSlidingWindow(int[] nums,int k){\n  }\n}","class Solution{\npublic:\n  vector<int> maxSlidingWindow(vector<int>&nums,int k){\n  }\n};")},
  { title:"Find All Anagrams in a String", difficulty:"Medium", description:"Find all anagram starting positions of pattern p in string s.", snippets: s("function findAnagrams(s,p){\n  \n}","def findAnagrams(s,p):\n    pass","class Solution{\n  public List<Integer> findAnagrams(String s,String p){\n  }\n}","class Solution{\npublic:\n  vector<int> findAnagrams(string s,string p){\n  }\n};")},
  { title:"Longest Palindromic Substring", difficulty:"Medium", description:"Find the longest palindromic substring in s.", snippets: s("function longestPalindrome(s){\n  \n}","def longestPalindrome(s):\n    pass","class Solution{\n  public String longestPalindrome(String s){\n  }\n}","class Solution{\npublic:\n  string longestPalindrome(string s){\n  }\n};")},
  { title:"Group Anagrams", difficulty:"Medium", description:"Group strings that are anagrams of each other.", snippets: s("function groupAnagrams(strs){\n  \n}","def groupAnagrams(strs):\n    pass","class Solution{\n  public List<List<String>> groupAnagrams(String[] strs){\n  }\n}","class Solution{\npublic:\n  vector<vector<string>> groupAnagrams(vector<string>&strs){\n  }\n};")},
  { title:"Alien Dictionary", difficulty:"Hard", description:"Given a sorted dictionary of an alien language, find the order of characters.", snippets: s("function alienOrder(words){\n  \n}","def alienOrder(words):\n    pass","class Solution{\n  public String alienOrder(String[] words){\n  }\n}","class Solution{\npublic:\n  string alienOrder(vector<string>&words){\n  }\n};")},
  { title:"Pacific Atlantic Water Flow", difficulty:"Medium", description:"Find cells where water can flow to both Pacific and Atlantic ocean.", snippets: s("function pacificAtlantic(heights){\n  \n}","def pacificAtlantic(heights):\n    pass","class Solution{\n  public List<List<Integer>> pacificAtlantic(int[][] heights){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> pacificAtlantic(vector<vector<int>>&heights){\n  }\n};")},
  { title:"Course Schedule", difficulty:"Medium", description:"Determine if you can finish all courses given prerequisites (cycle detection).", snippets: s("function canFinish(n,pre){\n  \n}","def canFinish(n,pre):\n    pass","class Solution{\n  public boolean canFinish(int n,int[][] pre){\n  }\n}","class Solution{\npublic:\n  bool canFinish(int n,vector<vector<int>>&pre){\n  }\n};")},
  { title:"Course Schedule II", difficulty:"Medium", description:"Return a valid course order using topological sort.", snippets: s("function findOrder(n,pre){\n  \n}","def findOrder(n,pre):\n    pass","class Solution{\n  public int[] findOrder(int n,int[][] pre){\n  }\n}","class Solution{\npublic:\n  vector<int> findOrder(int n,vector<vector<int>>&pre){\n  }\n};")},
  { title:"Network Delay Time", difficulty:"Medium", description:"Find the time until all nodes receive signal using Dijkstra.", snippets: s("function networkDelayTime(times,n,k){\n  \n}","def networkDelayTime(times,n,k):\n    pass","class Solution{\n  public int networkDelayTime(int[][] times,int n,int k){\n  }\n}","class Solution{\npublic:\n  int networkDelayTime(vector<vector<int>>&times,int n,int k){\n  }\n};")},
  { title:"Find the Celebrity", difficulty:"Medium", description:"Find the celebrity who knows nobody but everyone knows.", snippets: s("function findCelebrity(n){\n  \n}","def findCelebrity(n):\n    pass","class Solution{\n  public int findCelebrity(int n){\n  }\n}","class Solution{\npublic:\n  int findCelebrity(int n){\n  }\n};")},
  { title:"Design Hit Counter", difficulty:"Medium", description:"Design a hit counter that returns hits in the past 5 minutes.", snippets: s("class HitCounter{\n  hit(timestamp){}\n  getHits(timestamp){}\n}","class HitCounter:\n  def hit(self,t):pass\n  def getHits(self,t):pass","class HitCounter{\n  public void hit(int t){}\n  public int getHits(int t){}\n}","class HitCounter{\npublic:\n  void hit(int t){}\n  int getHits(int t){}\n};")},
  { title:"Design Tic-Tac-Toe", difficulty:"Medium", description:"Design a Tic-Tac-Toe game with O(1) move validation.", snippets: s("class TicTacToe{\n  constructor(n){}\n  move(r,c,p){}\n}","class TicTacToe:\n  def __init__(self,n):pass\n  def move(self,r,c,p):pass","class TicTacToe{\n  public TicTacToe(int n){}\n  public int move(int r,int c,int p){}\n}","class TicTacToe{\npublic:\n  TicTacToe(int n){}\n  int move(int r,int c,int p){}\n};")},
  { title:"Serialize and Deserialize Binary Tree", difficulty:"Hard", description:"Design an algorithm to serialize and deserialize a binary tree.", snippets: s("function serialize(root){\n  \n}\nfunction deserialize(data){\n  \n}","def serialize(root):\n    pass\ndef deserialize(data):\n    pass","class Codec{\n  public String serialize(TreeNode root){}\n  public TreeNode deserialize(String data){}\n}","class Codec{\npublic:\n  string serialize(TreeNode* root){}\n  TreeNode* deserialize(string data){}\n};")},
  { title:"Binary Tree Level Order Traversal", difficulty:"Medium", description:"Return the level order traversal of a binary tree.", snippets: s("function levelOrder(root){\n  \n}","def levelOrder(root):\n    pass","class Solution{\n  public List<List<Integer>> levelOrder(TreeNode root){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> levelOrder(TreeNode* root){\n  }\n};")},
  { title:"Subtree of Another Tree", difficulty:"Easy", description:"Check if tree t is a subtree of tree s.", snippets: s("function isSubtree(root,sub){\n  \n}","def isSubtree(root,sub):\n    pass","class Solution{\n  public boolean isSubtree(TreeNode root,TreeNode sub){\n  }\n}","class Solution{\npublic:\n  bool isSubtree(TreeNode* root,TreeNode* sub){\n  }\n};")},
  { title:"Kth Largest Element in an Array", difficulty:"Medium", description:"Find the kth largest element using quickselect or heap.", snippets: s("function findKthLargest(nums,k){\n  \n}","def findKthLargest(nums,k):\n    pass","class Solution{\n  public int findKthLargest(int[] nums,int k){\n  }\n}","class Solution{\npublic:\n  int findKthLargest(vector<int>&nums,int k){\n  }\n};")},
  { title:"Find Median from Data Stream", difficulty:"Hard", description:"Design a data structure that supports adding numbers and finding the median.", snippets: s("class MedianFinder{\n  addNum(num){}\n  findMedian(){}\n}","class MedianFinder:\n  def addNum(self,n):pass\n  def findMedian(self):pass","class MedianFinder{\n  public void addNum(int n){}\n  public double findMedian(){}\n}","class MedianFinder{\npublic:\n  void addNum(int n){}\n  double findMedian(){}\n};")},
].map(q => ({...q, company:'amazon'}));

const microsoft = [
  { title:"Valid Palindrome", difficulty:"Easy", description:"Check if string is palindrome after removing non-alphanumeric characters.", snippets: s("function isPalindrome(s){\n  \n}","def isPalindrome(s):\n    pass","class Solution{\n  public boolean isPalindrome(String s){\n  }\n}","class Solution{\npublic:\n  bool isPalindrome(string s){\n  }\n};")},
  { title:"Reverse Words in a String", difficulty:"Medium", description:"Reverse the words in a string, removing extra spaces.", snippets: s("function reverseWords(s){\n  \n}","def reverseWords(s):\n    pass","class Solution{\n  public String reverseWords(String s){\n  }\n}","class Solution{\npublic:\n  string reverseWords(string s){\n  }\n};")},
  { title:"Copy List with Random Pointer", difficulty:"Medium", description:"Deep copy a linked list with random pointers.", snippets: s("function copyRandomList(head){\n  \n}","def copyRandomList(head):\n    pass","class Solution{\n  public Node copyRandomList(Node head){\n  }\n}","class Solution{\npublic:\n  Node* copyRandomList(Node* head){\n  }\n};")},
  { title:"Flatten Binary Tree to Linked List", difficulty:"Medium", description:"Flatten a binary tree to a linked list in-place in preorder.", snippets: s("function flatten(root){\n  \n}","def flatten(root):\n    pass","class Solution{\n  public void flatten(TreeNode root){\n  }\n}","class Solution{\npublic:\n  void flatten(TreeNode* root){\n  }\n};")},
  { title:"Binary Tree Zigzag Level Order Traversal", difficulty:"Medium", description:"Return zigzag level order traversal of binary tree values.", snippets: s("function zigzagLevelOrder(root){\n  \n}","def zigzagLevelOrder(root):\n    pass","class Solution{\n  public List<List<Integer>> zigzagLevelOrder(TreeNode root){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> zigzagLevelOrder(TreeNode* root){\n  }\n};")},
  { title:"Maximum Depth of Binary Tree", difficulty:"Easy", description:"Find the maximum depth of a binary tree.", snippets: s("function maxDepth(root){\n  \n}","def maxDepth(root):\n    pass","class Solution{\n  public int maxDepth(TreeNode root){\n  }\n}","class Solution{\npublic:\n  int maxDepth(TreeNode* root){\n  }\n};")},
  { title:"Lowest Common Ancestor of BST", difficulty:"Medium", description:"Find the LCA of two nodes in a Binary Search Tree.", snippets: s("function lowestCommonAncestor(root,p,q){\n  \n}","def lowestCommonAncestor(root,p,q):\n    pass","class Solution{\n  public TreeNode lowestCommonAncestor(TreeNode root,TreeNode p,TreeNode q){\n  }\n}","class Solution{\npublic:\n  TreeNode* lowestCommonAncestor(TreeNode* root,TreeNode* p,TreeNode* q){\n  }\n};")},
  { title:"Convert Sorted Array to BST", difficulty:"Easy", description:"Convert a sorted array to a height-balanced BST.", snippets: s("function sortedArrayToBST(nums){\n  \n}","def sortedArrayToBST(nums):\n    pass","class Solution{\n  public TreeNode sortedArrayToBST(int[] nums){\n  }\n}","class Solution{\npublic:\n  TreeNode* sortedArrayToBST(vector<int>&nums){\n  }\n};")},
  { title:"Validate Binary Search Tree", difficulty:"Medium", description:"Determine if a binary tree is a valid BST.", snippets: s("function isValidBST(root){\n  \n}","def isValidBST(root):\n    pass","class Solution{\n  public boolean isValidBST(TreeNode root){\n  }\n}","class Solution{\npublic:\n  bool isValidBST(TreeNode* root){\n  }\n};")},
  { title:"Inorder Successor in BST", difficulty:"Medium", description:"Find the in-order successor of a node in a BST.", snippets: s("function inorderSuccessor(root,p){\n  \n}","def inorderSuccessor(root,p):\n    pass","class Solution{\n  public TreeNode inorderSuccessor(TreeNode root,TreeNode p){\n  }\n}","class Solution{\npublic:\n  TreeNode* inorderSuccessor(TreeNode* root,TreeNode* p){\n  }\n};")},
  { title:"Implement Trie (Prefix Tree)", difficulty:"Medium", description:"Implement a trie with insert, search, and startsWith methods.", snippets: s("class Trie{\n  insert(word){}\n  search(word){}\n  startsWith(prefix){}\n}","class Trie:\n  def insert(self,w):pass\n  def search(self,w):pass\n  def startsWith(self,p):pass","class Trie{\n  public void insert(String w){}\n  public boolean search(String w){}\n  public boolean startsWith(String p){}\n}","class Trie{\npublic:\n  void insert(string w){}\n  bool search(string w){}\n  bool startsWith(string p){}\n};")},
  { title:"Add and Search Word", difficulty:"Medium", description:"Implement a data structure supporting addWord and search with '.'.", snippets: s("class WordDictionary{\n  addWord(word){}\n  search(word){}\n}","class WordDictionary:\n  def addWord(self,w):pass\n  def search(self,w):pass","class WordDictionary{\n  public void addWord(String w){}\n  public boolean search(String w){}\n}","class WordDictionary{\npublic:\n  void addWord(string w){}\n  bool search(string w){}\n};")},
  { title:"Word Search", difficulty:"Medium", description:"Search for a word in a 2D board using DFS backtracking.", snippets: s("function exist(board,word){\n  \n}","def exist(board,word):\n    pass","class Solution{\n  public boolean exist(char[][] board,String word){\n  }\n}","class Solution{\npublic:\n  bool exist(vector<vector<char>>&board,string word){\n  }\n};")},
  { title:"Word Search II", difficulty:"Hard", description:"Find all words from a list that exist on the board using Trie + DFS.", snippets: s("function findWords(board,words){\n  \n}","def findWords(board,words):\n    pass","class Solution{\n  public List<String> findWords(char[][] board,String[] words){\n  }\n}","class Solution{\npublic:\n  vector<string> findWords(vector<vector<char>>&board,vector<string>&words){\n  }\n};")},
  { title:"Graph Valid Tree", difficulty:"Medium", description:"Determine if n nodes form a valid tree given edges.", snippets: s("function validTree(n,edges){\n  \n}","def validTree(n,edges):\n    pass","class Solution{\n  public boolean validTree(int n,int[][] edges){\n  }\n}","class Solution{\npublic:\n  bool validTree(int n,vector<vector<int>>&edges){\n  }\n};")},
  { title:"Number of Connected Components", difficulty:"Medium", description:"Count the number of connected components in an undirected graph.", snippets: s("function countComponents(n,edges){\n  \n}","def countComponents(n,edges):\n    pass","class Solution{\n  public int countComponents(int n,int[][] edges){\n  }\n}","class Solution{\npublic:\n  int countComponents(int n,vector<vector<int>>&edges){\n  }\n};")},
  { title:"Longest Consecutive Sequence", difficulty:"Medium", description:"Find the length of the longest consecutive sequence in O(n).", snippets: s("function longestConsecutive(nums){\n  \n}","def longestConsecutive(nums):\n    pass","class Solution{\n  public int longestConsecutive(int[] nums){\n  }\n}","class Solution{\npublic:\n  int longestConsecutive(vector<int>&nums){\n  }\n};")},
  { title:"Missing Number", difficulty:"Easy", description:"Find the missing number in an array containing n distinct numbers in [0, n].", snippets: s("function missingNumber(nums){\n  \n}","def missingNumber(nums):\n    pass","class Solution{\n  public int missingNumber(int[] nums){\n  }\n}","class Solution{\npublic:\n  int missingNumber(vector<int>&nums){\n  }\n};")},
  { title:"Single Number", difficulty:"Easy", description:"Find the element that appears only once using XOR.", snippets: s("function singleNumber(nums){\n  \n}","def singleNumber(nums):\n    pass","class Solution{\n  public int singleNumber(int[] nums){\n  }\n}","class Solution{\npublic:\n  int singleNumber(vector<int>&nums){\n  }\n};")},
  { title:"Counting Bits", difficulty:"Easy", description:"Return an array of the number of 1-bits for every number 0 to n.", snippets: s("function countBits(n){\n  \n}","def countBits(n):\n    pass","class Solution{\n  public int[] countBits(int n){\n  }\n}","class Solution{\npublic:\n  vector<int> countBits(int n){\n  }\n};")},
  { title:"Sum of Two Integers Without + Operator", difficulty:"Medium", description:"Calculate sum of two integers without using + or - operators.", snippets: s("function getSum(a,b){\n  \n}","def getSum(a,b):\n    pass","class Solution{\n  public int getSum(int a,int b){\n  }\n}","class Solution{\npublic:\n  int getSum(int a,int b){\n  }\n};")},
  { title:"Number of 1 Bits", difficulty:"Easy", description:"Count the number of 1-bits (Hamming weight) in an unsigned integer.", snippets: s("function hammingWeight(n){\n  \n}","def hammingWeight(n):\n    pass","class Solution{\n  public int hammingWeight(int n){\n  }\n}","class Solution{\npublic:\n  int hammingWeight(uint32_t n){\n  }\n};")},
  { title:"Reverse Bits", difficulty:"Easy", description:"Reverse bits of a 32-bit unsigned integer.", snippets: s("function reverseBits(n){\n  \n}","def reverseBits(n):\n    pass","class Solution{\n  public int reverseBits(int n){\n  }\n}","class Solution{\npublic:\n  uint32_t reverseBits(uint32_t n){\n  }\n};")},
  { title:"Power of Two", difficulty:"Easy", description:"Determine whether an integer is a power of two.", snippets: s("function isPowerOfTwo(n){\n  \n}","def isPowerOfTwo(n):\n    pass","class Solution{\n  public boolean isPowerOfTwo(int n){\n  }\n}","class Solution{\npublic:\n  bool isPowerOfTwo(int n){\n  }\n};")},
  { title:"Excel Sheet Column Number", difficulty:"Easy", description:"Given a column title, return its corresponding column number.", snippets: s("function titleToNumber(col){\n  \n}","def titleToNumber(col):\n    pass","class Solution{\n  public int titleToNumber(String col){\n  }\n}","class Solution{\npublic:\n  int titleToNumber(string col){\n  }\n};")},
  { title:"Integer to Roman", difficulty:"Medium", description:"Convert an integer to a Roman numeral string.", snippets: s("function intToRoman(num){\n  \n}","def intToRoman(num):\n    pass","class Solution{\n  public String intToRoman(int num){\n  }\n}","class Solution{\npublic:\n  string intToRoman(int num){\n  }\n};")},
  { title:"Roman to Integer", difficulty:"Easy", description:"Convert a Roman numeral string to an integer.", snippets: s("function romanToInt(s){\n  \n}","def romanToInt(s):\n    pass","class Solution{\n  public int romanToInt(String s){\n  }\n}","class Solution{\npublic:\n  int romanToInt(string s){\n  }\n};")},
  { title:"Unique Paths", difficulty:"Medium", description:"Count unique paths in an m x n grid from top-left to bottom-right.", snippets: s("function uniquePaths(m,n){\n  \n}","def uniquePaths(m,n):\n    pass","class Solution{\n  public int uniquePaths(int m,int n){\n  }\n}","class Solution{\npublic:\n  int uniquePaths(int m,int n){\n  }\n};")},
  { title:"Minimum Path Sum", difficulty:"Medium", description:"Find the path from top-left to bottom-right with minimum sum.", snippets: s("function minPathSum(grid){\n  \n}","def minPathSum(grid):\n    pass","class Solution{\n  public int minPathSum(int[][] grid){\n  }\n}","class Solution{\npublic:\n  int minPathSum(vector<vector<int>>&grid){\n  }\n};")},
  { title:"Edit Distance", difficulty:"Hard", description:"Find the minimum edit distance (Levenshtein) between two strings.", snippets: s("function minDistance(w1,w2){\n  \n}","def minDistance(w1,w2):\n    pass","class Solution{\n  public int minDistance(String w1,String w2){\n  }\n}","class Solution{\npublic:\n  int minDistance(string w1,string w2){\n  }\n};")},
].map(q => ({...q, company:'microsoft'}));

const meta = [
  { title:"Product of Array Except Self", difficulty:"Medium", description:"Return array where each element is the product of all others. No division, O(n).", snippets: s("function productExceptSelf(nums){\n  \n}","def productExceptSelf(nums):\n    pass","class Solution{\n  public int[] productExceptSelf(int[] nums){\n  }\n}","class Solution{\npublic:\n  vector<int> productExceptSelf(vector<int>&nums){\n  }\n};")},
  { title:"Subarray Sum Equals K", difficulty:"Medium", description:"Count subarrays with sum equal to k using prefix sums.", snippets: s("function subarraySum(nums,k){\n  \n}","def subarraySum(nums,k):\n    pass","class Solution{\n  public int subarraySum(int[] nums,int k){\n  }\n}","class Solution{\npublic:\n  int subarraySum(vector<int>&nums,int k){\n  }\n};")},
  { title:"Valid Anagram", difficulty:"Easy", description:"Determine if two strings are anagrams of each other.", snippets: s("function isAnagram(s,t){\n  \n}","def isAnagram(s,t):\n    pass","class Solution{\n  public boolean isAnagram(String s,String t){\n  }\n}","class Solution{\npublic:\n  bool isAnagram(string s,string t){\n  }\n};")},
  { title:"Binary Search", difficulty:"Easy", description:"Implement binary search on a sorted array.", snippets: s("function search(nums,target){\n  \n}","def search(nums,target):\n    pass","class Solution{\n  public int search(int[] nums,int target){\n  }\n}","class Solution{\npublic:\n  int search(vector<int>&nums,int target){\n  }\n};")},
  { title:"First Bad Version", difficulty:"Easy", description:"Find the first bad version using a binary-search-based API.", snippets: s("function solution(isBadVersion){\n  return function(n){\n  }\n}","def firstBadVersion(n):\n    pass","class Solution{\n  public int firstBadVersion(int n){\n  }\n}","class Solution{\npublic:\n  int firstBadVersion(int n){\n  }\n};")},
  { title:"Flatten Nested List Iterator", difficulty:"Medium", description:"Implement an iterator that flattens a nested list of integers.", snippets: s("class NestedIterator{\n  constructor(list){}\n  next(){}\n  hasNext(){}\n}","class NestedIterator:\n  def __init__(self,lst):pass\n  def next(self):pass\n  def hasNext(self):pass","class NestedIterator{\n  public NestedIterator(List<NestedInteger> l){}\n  public int next(){}\n  public boolean hasNext(){}\n}","class NestedIterator{\npublic:\n  NestedIterator(vector<NestedInteger>&l){}\n  int next(){}\n  bool hasNext(){}\n};")},
  { title:"Move Zeroes", difficulty:"Easy", description:"Move all zeroes to the end while maintaining relative order.", snippets: s("function moveZeroes(nums){\n  \n}","def moveZeroes(nums):\n    pass","class Solution{\n  public void moveZeroes(int[] nums){\n  }\n}","class Solution{\npublic:\n  void moveZeroes(vector<int>&nums){\n  }\n};")},
  { title:"Meeting Rooms", difficulty:"Easy", description:"Determine if a person can attend all meetings (no overlapping intervals).", snippets: s("function canAttendMeetings(intervals){\n  \n}","def canAttendMeetings(intervals):\n    pass","class Solution{\n  public boolean canAttendMeetings(int[][] intervals){\n  }\n}","class Solution{\npublic:\n  bool canAttendMeetings(vector<vector<int>>&intervals){\n  }\n};")},
  { title:"Meeting Rooms II", difficulty:"Medium", description:"Find the minimum number of conference rooms required.", snippets: s("function minMeetingRooms(intervals){\n  \n}","def minMeetingRooms(intervals):\n    pass","class Solution{\n  public int minMeetingRooms(int[][] intervals){\n  }\n}","class Solution{\npublic:\n  int minMeetingRooms(vector<vector<int>>&intervals){\n  }\n};")},
  { title:"Encode and Decode Strings", difficulty:"Medium", description:"Design encode and decode functions to serialize/deserialize a list of strings.", snippets: s("function encode(strs){\n  \n}\nfunction decode(s){\n  \n}","def encode(strs):\n    pass\ndef decode(s):\n    pass","class Codec{\n  public String encode(List<String> strs){}\n  public List<String> decode(String s){}\n}","class Codec{\npublic:\n  string encode(vector<string>&strs){}\n  vector<string> decode(string s){}\n};")},
  { title:"Squares of a Sorted Array", difficulty:"Easy", description:"Return array of squares of sorted integers, sorted in non-decreasing order.", snippets: s("function sortedSquares(nums){\n  \n}","def sortedSquares(nums):\n    pass","class Solution{\n  public int[] sortedSquares(int[] nums){\n  }\n}","class Solution{\npublic:\n  vector<int> sortedSquares(vector<int>&nums){\n  }\n};")},
  { title:"Insert Interval", difficulty:"Medium", description:"Insert a new interval into a sorted list of non-overlapping intervals.", snippets: s("function insert(intervals,newInterval){\n  \n}","def insert(intervals,newInterval):\n    pass","class Solution{\n  public int[][] insert(int[][] intervals,int[] newInterval){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> insert(vector<vector<int>>&intervals,vector<int>&newInterval){\n  }\n};")},
  { title:"Interval List Intersections", difficulty:"Medium", description:"Find the intersection of two lists of closed intervals.", snippets: s("function intervalIntersection(A,B){\n  \n}","def intervalIntersection(A,B):\n    pass","class Solution{\n  public int[][] intervalIntersection(int[][] A,int[][] B){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> intervalIntersection(vector<vector<int>>&A,vector<vector<int>>&B){\n  }\n};")},
  { title:"Non-overlapping Intervals", difficulty:"Medium", description:"Find the minimum number of intervals to remove to make the rest non-overlapping.", snippets: s("function eraseOverlapIntervals(intervals){\n  \n}","def eraseOverlapIntervals(intervals):\n    pass","class Solution{\n  public int eraseOverlapIntervals(int[][] intervals){\n  }\n}","class Solution{\npublic:\n  int eraseOverlapIntervals(vector<vector<int>>&intervals){\n  }\n};")},
  { title:"Task Scheduler", difficulty:"Medium", description:"Find the minimum number of intervals needed to finish all tasks with cooldown n.", snippets: s("function leastInterval(tasks,n){\n  \n}","def leastInterval(tasks,n):\n    pass","class Solution{\n  public int leastInterval(char[] tasks,int n){\n  }\n}","class Solution{\npublic:\n  int leastInterval(vector<char>&tasks,int n){\n  }\n};")},
  { title:"Hand of Straights", difficulty:"Medium", description:"Determine if cards can be rearranged into groups of W consecutive cards.", snippets: s("function isNStraightHand(hand,groupSize){\n  \n}","def isNStraightHand(hand,W):\n    pass","class Solution{\n  public boolean isNStraightHand(int[] hand,int groupSize){\n  }\n}","class Solution{\npublic:\n  bool isNStraightHand(vector<int>&hand,int groupSize){\n  }\n};")},
  { title:"Contiguous Array", difficulty:"Medium", description:"Find the maximum length subarray with equal numbers of 0 and 1.", snippets: s("function findMaxLength(nums){\n  \n}","def findMaxLength(nums):\n    pass","class Solution{\n  public int findMaxLength(int[] nums){\n  }\n}","class Solution{\npublic:\n  int findMaxLength(vector<int>&nums){\n  }\n};")},
  { title:"Max Consecutive Ones III", difficulty:"Medium", description:"Find max consecutive 1s after flipping at most k 0s.", snippets: s("function longestOnes(nums,k){\n  \n}","def longestOnes(nums,k):\n    pass","class Solution{\n  public int longestOnes(int[] nums,int k){\n  }\n}","class Solution{\npublic:\n  int longestOnes(vector<int>&nums,int k){\n  }\n};")},
  { title:"Accounts Merge", difficulty:"Medium", description:"Merge accounts that share a common email using Union-Find or DFS.", snippets: s("function accountsMerge(accounts){\n  \n}","def accountsMerge(accounts):\n    pass","class Solution{\n  public List<List<String>> accountsMerge(List<List<String>> accounts){\n  }\n}","class Solution{\npublic:\n  vector<vector<string>> accountsMerge(vector<vector<string>>&accounts){\n  }\n};")},
  { title:"Friend Circles", difficulty:"Medium", description:"Find the number of friend circles using Union-Find or DFS.", snippets: s("function findCircleNum(isConnected){\n  \n}","def findCircleNum(isConnected):\n    pass","class Solution{\n  public int findCircleNum(int[][] isConnected){\n  }\n}","class Solution{\npublic:\n  int findCircleNum(vector<vector<int>>&isConnected){\n  }\n};")},
  { title:"Redundant Connection", difficulty:"Medium", description:"Find the edge that, when removed, results in a tree from Union-Find.", snippets: s("function findRedundantConnection(edges){\n  \n}","def findRedundantConnection(edges):\n    pass","class Solution{\n  public int[] findRedundantConnection(int[][] edges){\n  }\n}","class Solution{\npublic:\n  vector<int> findRedundantConnection(vector<vector<int>>&edges){\n  }\n};")},
  { title:"Count of Smaller Numbers After Self", difficulty:"Hard", description:"Count smaller elements to the right of each element using merge sort or BIT.", snippets: s("function countSmaller(nums){\n  \n}","def countSmaller(nums):\n    pass","class Solution{\n  public List<Integer> countSmaller(int[] nums){\n  }\n}","class Solution{\npublic:\n  vector<int> countSmaller(vector<int>&nums){\n  }\n};")},
  { title:"Largest Rectangle in Histogram", difficulty:"Hard", description:"Find the area of the largest rectangle in a histogram using a stack.", snippets: s("function largestRectangleArea(heights){\n  \n}","def largestRectangleArea(heights):\n    pass","class Solution{\n  public int largestRectangleArea(int[] heights){\n  }\n}","class Solution{\npublic:\n  int largestRectangleArea(vector<int>&heights){\n  }\n};")},
  { title:"Maximal Rectangle", difficulty:"Hard", description:"Find the largest rectangle containing only 1s in a binary matrix.", snippets: s("function maximalRectangle(matrix){\n  \n}","def maximalRectangle(matrix):\n    pass","class Solution{\n  public int maximalRectangle(char[][] matrix){\n  }\n}","class Solution{\npublic:\n  int maximalRectangle(vector<vector<char>>&matrix){\n  }\n};")},
  { title:"Basic Calculator II", difficulty:"Medium", description:"Implement a calculator to evaluate a string expression with +, -, *, /.", snippets: s("function calculate(s){\n  \n}","def calculate(s):\n    pass","class Solution{\n  public int calculate(String s){\n  }\n}","class Solution{\npublic:\n  int calculate(string s){\n  }\n};")},
  { title:"Evaluate Reverse Polish Notation", difficulty:"Medium", description:"Evaluate the value of an arithmetic expression in Reverse Polish Notation.", snippets: s("function evalRPN(tokens){\n  \n}","def evalRPN(tokens):\n    pass","class Solution{\n  public int evalRPN(String[] tokens){\n  }\n}","class Solution{\npublic:\n  int evalRPN(vector<string>&tokens){\n  }\n};")},
  { title:"Daily Temperatures", difficulty:"Medium", description:"Return days until a warmer temperature for each day using a monotonic stack.", snippets: s("function dailyTemperatures(temps){\n  \n}","def dailyTemperatures(temps):\n    pass","class Solution{\n  public int[] dailyTemperatures(int[] temps){\n  }\n}","class Solution{\npublic:\n  vector<int> dailyTemperatures(vector<int>&temps){\n  }\n};")},
  { title:"Car Fleet", difficulty:"Medium", description:"Count car fleets arriving at the destination.", snippets: s("function carFleet(target,pos,speed){\n  \n}","def carFleet(target,pos,speed):\n    pass","class Solution{\n  public int carFleet(int target,int[] pos,int[] speed){\n  }\n}","class Solution{\npublic:\n  int carFleet(int target,vector<int>&pos,vector<int>&speed){\n  }\n};")},
  { title:"Largest Color Value in Directed Graph", difficulty:"Hard", description:"Find the largest color value of any valid path in a directed graph.", snippets: s("function largestPathValue(colors,edges){\n  \n}","def largestPathValue(colors,edges):\n    pass","class Solution{\n  public int largestPathValue(String colors,int[][] edges){\n  }\n}","class Solution{\npublic:\n  int largestPathValue(string colors,vector<vector<int>>&edges){\n  }\n};")},
].map(q => ({...q, company:'meta'}));

const seedDB = async () => {
  try {
    await Question.deleteMany({});
    const all = [...google, ...amazon, ...microsoft, ...meta];
    await Question.insertMany(all);
    console.log(`Seeded ${all.length} questions! (${google.length} Google, ${amazon.length} Amazon, ${microsoft.length} Microsoft, ${meta.length} Meta)`);
    process.exit(0);
  } catch (err) {
    console.error("Seed Error:", err);
    process.exit(1);
  }
};

seedDB();
