import mongoose from "mongoose";
import dotenv from "dotenv";
import Question from "../models/question.model.js";
dotenv.config();

mongoose.connect(process.env.MONGODB_URL)
  .then(() => console.log("Connected to MongoDB"))
  .catch(err => { console.error(err); process.exit(1); });

const s = (js, py, java, cpp) => ({ javascript: js, python: py, java, cpp });
const fn = (name, args='') => s(
  `function ${name}(${args}) {\n  // write your code here\n  \n}`,
  `def ${name}(${args.replace(/,/g,',').replace(/ /g,' ')}):\n    pass`,
  `class Solution {\n    public void ${name}(${args}) {\n    }\n}`,
  `class Solution {\npublic:\n    void ${name}() {\n    }\n};`
);

const netflix = [
  { title:"Merge k Sorted Lists", difficulty:"Hard", description:"Merge k sorted linked lists and return one sorted list using a min-heap.", snippets:s("function mergeKLists(lists){\n  \n}","def mergeKLists(lists):\n    pass","class Solution{\n  public ListNode mergeKLists(ListNode[] lists){\n  }\n}","class Solution{\npublic:\n  ListNode* mergeKLists(vector<ListNode*>&lists){\n  }\n};")},
  { title:"Rotate Image", difficulty:"Medium", description:"Rotate an n×n matrix 90 degrees clockwise in-place.", snippets:s("function rotate(matrix){\n  \n}","def rotate(matrix):\n    pass","class Solution{\n  public void rotate(int[][] matrix){\n  }\n}","class Solution{\npublic:\n  void rotate(vector<vector<int>>&matrix){\n  }\n};")},
  { title:"First Missing Positive", difficulty:"Hard", description:"Find the smallest missing positive integer in O(n) time and O(1) space.", snippets:s("function firstMissingPositive(nums){\n  \n}","def firstMissingPositive(nums):\n    pass","class Solution{\n  public int firstMissingPositive(int[] nums){\n  }\n}","class Solution{\npublic:\n  int firstMissingPositive(vector<int>&nums){\n  }\n};")},
  { title:"Find Duplicate Number", difficulty:"Medium", description:"Find the duplicate in an array of n+1 integers using Floyd's cycle detection.", snippets:s("function findDuplicate(nums){\n  \n}","def findDuplicate(nums):\n    pass","class Solution{\n  public int findDuplicate(int[] nums){\n  }\n}","class Solution{\npublic:\n  int findDuplicate(vector<int>&nums){\n  }\n};")},
  { title:"Longest Palindromic Subsequence", difficulty:"Medium", description:"Find the length of the longest palindromic subsequence using DP.", snippets:s("function longestPalindromeSubseq(s){\n  \n}","def longestPalindromeSubseq(s):\n    pass","class Solution{\n  public int longestPalindromeSubseq(String s){\n  }\n}","class Solution{\npublic:\n  int longestPalindromeSubseq(string s){\n  }\n};")},
  { title:"Burst Balloons", difficulty:"Hard", description:"Maximize coins from bursting balloons using interval DP.", snippets:s("function maxCoins(nums){\n  \n}","def maxCoins(nums):\n    pass","class Solution{\n  public int maxCoins(int[] nums){\n  }\n}","class Solution{\npublic:\n  int maxCoins(vector<int>&nums){\n  }\n};")},
  { title:"Regular Expression Matching", difficulty:"Hard", description:"Implement regex matching with '.' and '*' support.", snippets:s("function isMatch(s,p){\n  \n}","def isMatch(s,p):\n    pass","class Solution{\n  public boolean isMatch(String s,String p){\n  }\n}","class Solution{\npublic:\n  bool isMatch(string s,string p){\n  }\n};")},
  { title:"Wildcard Matching", difficulty:"Hard", description:"Implement wildcard matching with '?' and '*' support.", snippets:s("function isMatch(s,p){\n  \n}","def isMatch(s,p):\n    pass","class Solution{\n  public boolean isMatch(String s,String p){\n  }\n}","class Solution{\npublic:\n  bool isMatch(string s,string p){\n  }\n};")},
  { title:"Jump Game III", difficulty:"Medium", description:"Can you reach any index with value 0, jumping left or right by arr[i]?", snippets:s("function canReach(arr,start){\n  \n}","def canReach(arr,start):\n    pass","class Solution{\n  public boolean canReach(int[] arr,int start){\n  }\n}","class Solution{\npublic:\n  bool canReach(vector<int>&arr,int start){\n  }\n};")},
  { title:"Decode String", difficulty:"Medium", description:"Decode an encoded string like '3[a]2[bc]' → 'aaabcbc' using a stack.", snippets:s("function decodeString(s){\n  \n}","def decodeString(s):\n    pass","class Solution{\n  public String decodeString(String s){\n  }\n}","class Solution{\npublic:\n  string decodeString(string s){\n  }\n};")},
].map(q=>({...q, company:'netflix'}));

const apple = [
  { title:"Kth Smallest Element in BST", difficulty:"Medium", description:"Find the kth smallest element in a BST using in-order traversal.", snippets:s("function kthSmallest(root,k){\n  \n}","def kthSmallest(root,k):\n    pass","class Solution{\n  public int kthSmallest(TreeNode root,int k){\n  }\n}","class Solution{\npublic:\n  int kthSmallest(TreeNode* root,int k){\n  }\n};")},
  { title:"Time Based Key-Value Store", difficulty:"Medium", description:"Design a KV store that stores multiple values per key with timestamps.", snippets:s("class TimeMap{\n  set(key,val,ts){}\n  get(key,ts){}\n}","class TimeMap:\n  def set(self,k,v,t):pass\n  def get(self,k,t):pass","class TimeMap{\n  public void set(String k,String v,int t){}\n  public String get(String k,int t){}\n}","class TimeMap{\npublic:\n  void set(string k,string v,int t){}\n  string get(string k,int t){}\n};")},
  { title:"Swap Nodes in Pairs", difficulty:"Medium", description:"Swap every two adjacent nodes in a linked list.", snippets:s("function swapPairs(head){\n  \n}","def swapPairs(head):\n    pass","class Solution{\n  public ListNode swapPairs(ListNode head){\n  }\n}","class Solution{\npublic:\n  ListNode* swapPairs(ListNode* head){\n  }\n};")},
  { title:"Maximum Binary Tree", difficulty:"Medium", description:"Construct a binary tree where each node is the max of its subarray.", snippets:s("function constructMaximumBinaryTree(nums){\n  \n}","def constructMaximumBinaryTree(nums):\n    pass","class Solution{\n  public TreeNode constructMaximumBinaryTree(int[] nums){\n  }\n}","class Solution{\npublic:\n  TreeNode* constructMaximumBinaryTree(vector<int>&nums){\n  }\n};")},
  { title:"Diagonal Traverse", difficulty:"Medium", description:"Return all elements of a matrix in diagonal order.", snippets:s("function findDiagonalOrder(mat){\n  \n}","def findDiagonalOrder(mat):\n    pass","class Solution{\n  public int[] findDiagonalOrder(int[][] mat){\n  }\n}","class Solution{\npublic:\n  vector<int> findDiagonalOrder(vector<vector<int>>&mat){\n  }\n};")},
  { title:"Next Permutation", difficulty:"Medium", description:"Find the next lexicographically greater permutation in-place.", snippets:s("function nextPermutation(nums){\n  \n}","def nextPermutation(nums):\n    pass","class Solution{\n  public void nextPermutation(int[] nums){\n  }\n}","class Solution{\npublic:\n  void nextPermutation(vector<int>&nums){\n  }\n};")},
  { title:"Surrounded Regions", difficulty:"Medium", description:"Capture regions surrounded by X; O boarder-connected regions are not captured.", snippets:s("function solve(board){\n  \n}","def solve(board):\n    pass","class Solution{\n  public void solve(char[][] board){\n  }\n}","class Solution{\npublic:\n  void solve(vector<vector<char>>&board){\n  }\n};")},
  { title:"Minimum Falling Path Sum", difficulty:"Medium", description:"Find the minimum sum of a falling path through an n×n matrix.", snippets:s("function minFallingPathSum(matrix){\n  \n}","def minFallingPathSum(matrix):\n    pass","class Solution{\n  public int minFallingPathSum(int[][] matrix){\n  }\n}","class Solution{\npublic:\n  int minFallingPathSum(vector<vector<int>>&matrix){\n  }\n};")},
  { title:"Max Area of Island", difficulty:"Medium", description:"Find the maximum area of an island in a 2D grid.", snippets:s("function maxAreaOfIsland(grid){\n  \n}","def maxAreaOfIsland(grid):\n    pass","class Solution{\n  public int maxAreaOfIsland(int[][] grid){\n  }\n}","class Solution{\npublic:\n  int maxAreaOfIsland(vector<vector<int>>&grid){\n  }\n};")},
  { title:"Design Parking System", difficulty:"Easy", description:"Design a parking system with big, medium, and small spots.", snippets:s("class ParkingSystem{\n  constructor(big,med,small){}\n  addCar(type){}\n}","class ParkingSystem:\n  def __init__(self,b,m,s):pass\n  def addCar(self,t):pass","class ParkingSystem{\n  public ParkingSystem(int b,int m,int s){}\n  public boolean addCar(int type){}\n}","class ParkingSystem{\npublic:\n  ParkingSystem(int b,int m,int s){}\n  bool addCar(int type){}\n};")},
].map(q=>({...q, company:'apple'}));

const linkedin = [
  { title:"Insert Delete GetRandom O(1)", difficulty:"Medium", description:"Design a set that supports insert, remove, and getRandom in O(1).", snippets:s("class RandomizedSet{\n  insert(val){}\n  remove(val){}\n  getRandom(){}\n}","class RandomizedSet:\n  def insert(self,v):pass\n  def remove(self,v):pass\n  def getRandom(self):pass","class RandomizedSet{\n  public boolean insert(int v){}\n  public boolean remove(int v){}\n  public int getRandom(){}\n}","class RandomizedSet{\npublic:\n  bool insert(int v){}\n  bool remove(int v){}\n  int getRandom(){}\n};")},
  { title:"Isomorphic Strings", difficulty:"Easy", description:"Determine if two strings are isomorphic (same structure mapping).", snippets:s("function isIsomorphic(s,t){\n  \n}","def isIsomorphic(s,t):\n    pass","class Solution{\n  public boolean isIsomorphic(String s,String t){\n  }\n}","class Solution{\npublic:\n  bool isIsomorphic(string s,string t){\n  }\n};")},
  { title:"Can Place Flowers", difficulty:"Easy", description:"Check if n flowers can be planted in a flowerbed with no two adjacent.", snippets:s("function canPlaceFlowers(bed,n){\n  \n}","def canPlaceFlowers(bed,n):\n    pass","class Solution{\n  public boolean canPlaceFlowers(int[] bed,int n){\n  }\n}","class Solution{\npublic:\n  bool canPlaceFlowers(vector<int>&bed,int n){\n  }\n};")},
  { title:"Nested List Weight Sum", difficulty:"Medium", description:"Return sum of all integers weighted by their depth in a nested list.", snippets:s("function depthSum(nestedList){\n  \n}","def depthSum(nestedList):\n    pass","class Solution{\n  public int depthSum(List<NestedInteger> nestedList){\n  }\n}","class Solution{\npublic:\n  int depthSum(vector<NestedInteger>&nestedList){\n  }\n};")},
  { title:"Second Minimum Node in Binary Tree", difficulty:"Easy", description:"Find the second minimum value in a binary tree.", snippets:s("function findSecondMinimumValue(root){\n  \n}","def findSecondMinimumValue(root):\n    pass","class Solution{\n  public int findSecondMinimumValue(TreeNode root){\n  }\n}","class Solution{\npublic:\n  int findSecondMinimumValue(TreeNode* root){\n  }\n};")},
  { title:"Shortest Word Distance", difficulty:"Easy", description:"Find the shortest distance between two words in an array.", snippets:s("function shortestDistance(words,w1,w2){\n  \n}","def shortestDistance(words,w1,w2):\n    pass","class Solution{\n  public int shortestDistance(String[] words,String w1,String w2){\n  }\n}","class Solution{\npublic:\n  int shortestDistance(vector<string>&words,string w1,string w2){\n  }\n};")},
  { title:"Find Peak Element", difficulty:"Medium", description:"Find a peak element (greater than both neighbors) in O(log n).", snippets:s("function findPeakElement(nums){\n  \n}","def findPeakElement(nums):\n    pass","class Solution{\n  public int findPeakElement(int[] nums){\n  }\n}","class Solution{\npublic:\n  int findPeakElement(vector<int>&nums){\n  }\n};")},
  { title:"Maximum Product Subarray", difficulty:"Medium", description:"Find the contiguous subarray with the largest product.", snippets:s("function maxProduct(nums){\n  \n}","def maxProduct(nums):\n    pass","class Solution{\n  public int maxProduct(int[] nums){\n  }\n}","class Solution{\npublic:\n  int maxProduct(vector<int>&nums){\n  }\n};")},
].map(q=>({...q, company:'linkedin'}));

const uber = [
  { title:"Reorganize String", difficulty:"Medium", description:"Rearrange characters so no two adjacent are the same.", snippets:s("function reorganizeString(s){\n  \n}","def reorganizeString(s):\n    pass","class Solution{\n  public String reorganizeString(String s){\n  }\n}","class Solution{\npublic:\n  string reorganizeString(string s){\n  }\n};")},
  { title:"Verifying an Alien Dictionary", difficulty:"Easy", description:"Given words and a custom alphabet order, verify if words are sorted.", snippets:s("function isAlienSorted(words,order){\n  \n}","def isAlienSorted(words,order):\n    pass","class Solution{\n  public boolean isAlienSorted(String[] words,String order){\n  }\n}","class Solution{\npublic:\n  bool isAlienSorted(vector<string>&words,string order){\n  }\n};")},
  { title:"Increasing Triplet Subsequence", difficulty:"Medium", description:"Determine if there's an increasing triplet subsequence in O(n) time.", snippets:s("function increasingTriplet(nums){\n  \n}","def increasingTriplet(nums):\n    pass","class Solution{\n  public boolean increasingTriplet(int[] nums){\n  }\n}","class Solution{\npublic:\n  bool increasingTriplet(vector<int>&nums){\n  }\n};")},
  { title:"Optimal Account Balancing", difficulty:"Hard", description:"Minimize transactions to settle all debts among a group.", snippets:s("function minTransfers(transactions){\n  \n}","def minTransfers(transactions):\n    pass","class Solution{\n  public int minTransfers(int[][] transactions){\n  }\n}","class Solution{\npublic:\n  int minTransfers(vector<vector<int>>&transactions){\n  }\n};")},
  { title:"Rearrange String k Distance Apart", difficulty:"Hard", description:"Rearrange so same characters are at least k distance apart.", snippets:s("function rearrangeString(s,k){\n  \n}","def rearrangeString(s,k):\n    pass","class Solution{\n  public String rearrangeString(String s,int k){\n  }\n}","class Solution{\npublic:\n  string rearrangeString(string s,int k){\n  }\n};")},
  { title:"Sum Root to Leaf Numbers", difficulty:"Medium", description:"Sum all numbers formed by root-to-leaf paths in a binary tree.", snippets:s("function sumNumbers(root){\n  \n}","def sumNumbers(root):\n    pass","class Solution{\n  public int sumNumbers(TreeNode root){\n  }\n}","class Solution{\npublic:\n  int sumNumbers(TreeNode* root){\n  }\n};")},
  { title:"Path Sum II", difficulty:"Medium", description:"Return all root-to-leaf paths where the path sum equals target.", snippets:s("function pathSum(root,target){\n  \n}","def pathSum(root,target):\n    pass","class Solution{\n  public List<List<Integer>> pathSum(TreeNode root,int target){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> pathSum(TreeNode* root,int target){\n  }\n};")},
  { title:"String Compression", difficulty:"Medium", description:"Compress a character array in-place using run-length encoding.", snippets:s("function compress(chars){\n  \n}","def compress(chars):\n    pass","class Solution{\n  public int compress(char[] chars){\n  }\n}","class Solution{\npublic:\n  int compress(vector<char>&chars){\n  }\n};")},
].map(q=>({...q, company:'uber'}));

const twitter = [
  { title:"Design Twitter", difficulty:"Medium", description:"Design a Twitter/X-like service with post tweet, follow, and news feed APIs.", snippets:s("class Twitter{\n  postTweet(userId,tweetId){}\n  getNewsFeed(userId){}\n  follow(f,fe){}\n  unfollow(f,fe){}\n}","class Twitter:\n  def postTweet(self,u,t):pass\n  def getNewsFeed(self,u):pass\n  def follow(self,f,fe):pass\n  def unfollow(self,f,fe):pass","class Twitter{\n  public void postTweet(int userId,int tweetId){}\n  public List<Integer> getNewsFeed(int userId){}\n  public void follow(int f,int fe){}\n  public void unfollow(int f,int fe){}\n}","class Twitter{\npublic:\n  void postTweet(int u,int t){}\n  vector<int> getNewsFeed(int u){}\n  void follow(int f,int fe){}\n  void unfollow(int f,int fe){}\n};")},
  { title:"Rank Teams by Votes", difficulty:"Medium", description:"Rank teams by votes using a stable custom sort.", snippets:s("function rankTeams(votes){\n  \n}","def rankTeams(votes):\n    pass","class Solution{\n  public String rankTeams(String[] votes){\n  }\n}","class Solution{\npublic:\n  string rankTeams(vector<string>&votes){\n  }\n};")},
  { title:"Number of Recent Calls", difficulty:"Easy", description:"Count requests in the past 3000 milliseconds using a queue.", snippets:s("class RecentCounter{\n  ping(t){}\n}","class RecentCounter:\n  def ping(self,t):pass","class RecentCounter{\n  public int ping(int t){}\n}","class RecentCounter{\npublic:\n  int ping(int t){}\n};")},
  { title:"Top K Frequent Words", difficulty:"Medium", description:"Return the k most frequent words sorted by frequency then alphabetically.", snippets:s("function topKFrequent(words,k){\n  \n}","def topKFrequent(words,k):\n    pass","class Solution{\n  public List<String> topKFrequent(String[] words,int k){\n  }\n}","class Solution{\npublic:\n  vector<string> topKFrequent(vector<string>&words,int k){\n  }\n};")},
  { title:"Stream of Characters", difficulty:"Hard", description:"Implement a query function to check if any word from wordlist ends with recent characters.", snippets:s("class StreamChecker{\n  constructor(words){}\n  query(letter){}\n}","class StreamChecker:\n  def __init__(self,words):pass\n  def query(self,c):pass","class StreamChecker{\n  public StreamChecker(String[] words){}\n  public boolean query(char c){}\n}","class StreamChecker{\npublic:\n  StreamChecker(vector<string>&words){}\n  bool query(char c){}\n};")},
  { title:"Palindrome Pairs", difficulty:"Hard", description:"Find all pairs of indices (i,j) such that words[i]+words[j] is a palindrome.", snippets:s("function palindromePairs(words){\n  \n}","def palindromePairs(words):\n    pass","class Solution{\n  public List<List<Integer>> palindromePairs(String[] words){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> palindromePairs(vector<string>&words){\n  }\n};")},
  { title:"Find the Difference", difficulty:"Easy", description:"Find the extra character added to string t compared to s.", snippets:s("function findTheDifference(s,t){\n  \n}","def findTheDifference(s,t):\n    pass","class Solution{\n  public char findTheDifference(String s,String t){\n  }\n}","class Solution{\npublic:\n  char findTheDifference(string s,string t){\n  }\n};")},
].map(q=>({...q, company:'twitter'}));

const adobe = [
  { title:"Max Points on a Line", difficulty:"Hard", description:"Find the maximum number of points that lie on the same straight line.", snippets:s("function maxPoints(points){\n  \n}","def maxPoints(points):\n    pass","class Solution{\n  public int maxPoints(int[][] points){\n  }\n}","class Solution{\npublic:\n  int maxPoints(vector<vector<int>>&points){\n  }\n};")},
  { title:"Rectangle Area", difficulty:"Medium", description:"Find the total area covered by two rectangles.", snippets:s("function computeArea(ax1,ay1,ax2,ay2,bx1,by1,bx2,by2){\n  \n}","def computeArea(*args):\n    pass","class Solution{\n  public int computeArea(int ax1,int ay1,int ax2,int ay2,int bx1,int by1,int bx2,int by2){\n  }\n}","class Solution{\npublic:\n  int computeArea(int ax1,int ay1,int ax2,int ay2,int bx1,int by1,int bx2,int by2){\n  }\n};")},
  { title:"Image Smoother", difficulty:"Easy", description:"Apply a smoothing filter to an image (average of 3x3 grid).", snippets:s("function imageSmoother(img){\n  \n}","def imageSmoother(img):\n    pass","class Solution{\n  public int[][] imageSmoother(int[][] img){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> imageSmoother(vector<vector<int>>&img){\n  }\n};")},
  { title:"Sparse Matrix Multiplication", difficulty:"Medium", description:"Multiply two sparse matrices efficiently.", snippets:s("function multiply(mat1,mat2){\n  \n}","def multiply(mat1,mat2):\n    pass","class Solution{\n  public int[][] multiply(int[][] mat1,int[][] mat2){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> multiply(vector<vector<int>>&mat1,vector<vector<int>>&mat2){\n  }\n};")},
  { title:"Bold Words in String", difficulty:"Medium", description:"Bold substrings of s that appear in words array using tags.", snippets:s("function addBoldTag(s,words){\n  \n}","def addBoldTag(s,words):\n    pass","class Solution{\n  public String addBoldTag(String s,String[] words){\n  }\n}","class Solution{\npublic:\n  string addBoldTag(string s,vector<string>&words){\n  }\n};")},
  { title:"24 Game", difficulty:"Hard", description:"Determine if four numbers can produce 24 using arithmetic ops.", snippets:s("function judgePoint24(cards){\n  \n}","def judgePoint24(cards):\n    pass","class Solution{\n  public boolean judgePoint24(int[] cards){\n  }\n}","class Solution{\npublic:\n  bool judgePoint24(vector<int>&cards){\n  }\n};")},
  { title:"Confusing Number", difficulty:"Easy", description:"Determine if a number becomes different when rotated 180 degrees.", snippets:s("function confusingNumber(n){\n  \n}","def confusingNumber(n):\n    pass","class Solution{\n  public boolean confusingNumber(int n){\n  }\n}","class Solution{\npublic:\n  bool confusingNumber(int n){\n  }\n};")},
].map(q=>({...q, company:'adobe'}));

const flipkart = [
  { title:"Sell Diminishing-Valued Colored Balls", difficulty:"Medium", description:"Maximize profit selling colored balls using a heap strategy.", snippets:s("function maxProfit(inventory,orders){\n  \n}","def maxProfit(inventory,orders):\n    pass","class Solution{\n  public int maxProfit(int[] inventory,int orders){\n  }\n}","class Solution{\npublic:\n  int maxProfit(vector<int>&inventory,int orders){\n  }\n};")},
  { title:"Minimum Number of Arrows to Burst Balloons", difficulty:"Medium", description:"Find minimum arrows to burst all balloons at given x-ranges.", snippets:s("function findMinArrowShots(points){\n  \n}","def findMinArrowShots(points):\n    pass","class Solution{\n  public int findMinArrowShots(int[][] points){\n  }\n}","class Solution{\npublic:\n  int findMinArrowShots(vector<vector<int>>&points){\n  }\n};")},
  { title:"Max Stack", difficulty:"Hard", description:"Design a Max Stack supporting push, pop, top, peekMax, and popMax.", snippets:s("class MaxStack{\n  push(x){}\n  pop(){}\n  top(){}\n  peekMax(){}\n  popMax(){}\n}","class MaxStack:\n  def push(self,x):pass\n  def pop(self):pass\n  def top(self):pass\n  def peekMax(self):pass\n  def popMax(self):pass","class MaxStack{\n  public void push(int x){}\n  public int pop(){}\n  public int top(){}\n  public int peekMax(){}\n  public int popMax(){}\n}","class MaxStack{\npublic:\n  void push(int x){}\n  int pop(){}\n  int top(){}\n  int peekMax(){}\n  int popMax(){}\n};")},
  { title:"Jump Game IV", difficulty:"Hard", description:"Find the minimum jumps to reach the last index using a graph BFS.", snippets:s("function minJumps(arr){\n  \n}","def minJumps(arr):\n    pass","class Solution{\n  public int minJumps(int[] arr){\n  }\n}","class Solution{\npublic:\n  int minJumps(vector<int>&arr){\n  }\n};")},
  { title:"Count Good Nodes in Binary Tree", difficulty:"Medium", description:"Count nodes where all ancestors on path from root have smaller or equal value.", snippets:s("function goodNodes(root){\n  \n}","def goodNodes(root):\n    pass","class Solution{\n  public int goodNodes(TreeNode root){\n  }\n}","class Solution{\npublic:\n  int goodNodes(TreeNode* root){\n  }\n};")},
  { title:"Find if Path Exists in Graph", difficulty:"Easy", description:"Find if a valid path exists from source to destination.", snippets:s("function validPath(n,edges,src,dst){\n  \n}","def validPath(n,edges,src,dst):\n    pass","class Solution{\n  public boolean validPath(int n,int[][] edges,int src,int dst){\n  }\n}","class Solution{\npublic:\n  bool validPath(int n,vector<vector<int>>&edges,int src,int dst){\n  }\n};")},
  { title:"Minimum Cost to Hire K Workers", difficulty:"Hard", description:"Hire exactly k workers at minimum cost respecting quality/wage ratios.", snippets:s("function mincostToHireWorkers(quality,wage,k){\n  \n}","def mincostToHireWorkers(quality,wage,k):\n    pass","class Solution{\n  public double mincostToHireWorkers(int[] quality,int[] wage,int k){\n  }\n}","class Solution{\npublic:\n  double mincostToHireWorkers(vector<int>&quality,vector<int>&wage,int k){\n  }\n};")},
].map(q=>({...q, company:'flipkart'}));

const seedNew = async () => {
  try {
    const newQuestions = [...netflix, ...apple, ...linkedin, ...uber, ...twitter, ...adobe, ...flipkart];
    const companies = ['netflix','apple','linkedin','uber','twitter','adobe','flipkart'];
    
    // Remove existing for these companies and insert fresh
    await Question.deleteMany({ company: { $in: companies } });
    await Question.insertMany(newQuestions);
    
    console.log(`Seeded ${newQuestions.length} new company questions!`);
    console.log(`Netflix:${netflix.length}, Apple:${apple.length}, LinkedIn:${linkedin.length}, Uber:${uber.length}, Twitter:${twitter.length}, Adobe:${adobe.length}, Flipkart:${flipkart.length}`);
    process.exit(0);
  } catch (err) {
    console.error('Seed Error:', err);
    process.exit(1);
  }
};

seedNew();
