import mongoose from "mongoose";
import dotenv from "dotenv";
import Question from "../models/question.model.js";
dotenv.config();

mongoose.connect(process.env.MONGODB_URL)
  .then(() => console.log("Connected to MongoDB"))
  .catch(err => { console.error(err); process.exit(1); });

const s = (js, py, java, cpp) => ({ javascript: js, python: py, java, cpp });

const other = [
  { title:"Fibonacci Number", difficulty:"Easy", description:"Return the nth Fibonacci number. F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2).", snippets:s("function fib(n){\n  \n}","def fib(n):\n    pass","class Solution{\n  public int fib(int n){\n  }\n}","class Solution{\npublic:\n  int fib(int n){\n  }\n};")},
  { title:"Pascal's Triangle", difficulty:"Easy", description:"Generate the first numRows rows of Pascal's triangle.", snippets:s("function generate(numRows){\n  \n}","def generate(numRows):\n    pass","class Solution{\n  public List<List<Integer>> generate(int numRows){\n  }\n}","class Solution{\npublic:\n  vector<vector<int>> generate(int numRows){\n  }\n};")},
  { title:"Majority Element", difficulty:"Easy", description:"Find the element that appears more than n/2 times using Boyer-Moore voting.", snippets:s("function majorityElement(nums){\n  \n}","def majorityElement(nums):\n    pass","class Solution{\n  public int majorityElement(int[] nums){\n  }\n}","class Solution{\npublic:\n  int majorityElement(vector<int>&nums){\n  }\n};")},
  { title:"Happy Number", difficulty:"Easy", description:"Determine if a number is happy (sum of squares of digits eventually reaches 1).", snippets:s("function isHappy(n){\n  \n}","def isHappy(n):\n    pass","class Solution{\n  public boolean isHappy(int n){\n  }\n}","class Solution{\npublic:\n  bool isHappy(int n){\n  }\n};")},
  { title:"Find All Numbers Disappeared in an Array", difficulty:"Easy", description:"Find all integers from 1 to n that are missing from the array.", snippets:s("function findDisappearedNumbers(nums){\n  \n}","def findDisappearedNumbers(nums):\n    pass","class Solution{\n  public List<Integer> findDisappearedNumbers(int[] nums){\n  }\n}","class Solution{\npublic:\n  vector<int> findDisappearedNumbers(vector<int>&nums){\n  }\n};")},
  { title:"Intersection of Two Arrays", difficulty:"Easy", description:"Return an array of unique elements present in both arrays.", snippets:s("function intersection(nums1,nums2){\n  \n}","def intersection(nums1,nums2):\n    pass","class Solution{\n  public int[] intersection(int[] nums1,int[] nums2){\n  }\n}","class Solution{\npublic:\n  vector<int> intersection(vector<int>&nums1,vector<int>&nums2){\n  }\n};")},
  { title:"Palindrome Number", difficulty:"Easy", description:"Determine if an integer is a palindrome without converting to string.", snippets:s("function isPalindrome(x){\n  \n}","def isPalindrome(x):\n    pass","class Solution{\n  public boolean isPalindrome(int x){\n  }\n}","class Solution{\npublic:\n  bool isPalindrome(long long x){\n  }\n};")},
  { title:"Reverse String", difficulty:"Easy", description:"Reverse a character array in-place using two pointers.", snippets:s("function reverseString(s){\n  \n}","def reverseString(s):\n    pass","class Solution{\n  public void reverseString(char[] s){\n  }\n}","class Solution{\npublic:\n  void reverseString(vector<char>&s){\n  }\n};")},
  { title:"First Unique Character in a String", difficulty:"Easy", description:"Return the index of the first non-repeating character in a string.", snippets:s("function firstUniqChar(s){\n  \n}","def firstUniqChar(s):\n    pass","class Solution{\n  public int firstUniqChar(String s){\n  }\n}","class Solution{\npublic:\n  int firstUniqChar(string s){\n  }\n};")},
  { title:"Merge Sorted Array", difficulty:"Easy", description:"Merge nums2 into nums1 in-place. Both are sorted.", snippets:s("function merge(nums1,m,nums2,n){\n  \n}","def merge(nums1,m,nums2,n):\n    pass","class Solution{\n  public void merge(int[] nums1,int m,int[] nums2,int n){\n  }\n}","class Solution{\npublic:\n  void merge(vector<int>&nums1,int m,vector<int>&nums2,int n){\n  }\n};")},
  { title:"Maximum Depth of N-ary Tree", difficulty:"Easy", description:"Find the maximum depth of an N-ary tree using BFS or DFS.", snippets:s("function maxDepth(root){\n  \n}","def maxDepth(root):\n    pass","class Solution{\n  public int maxDepth(Node root){\n  }\n}","class Solution{\npublic:\n  int maxDepth(Node* root){\n  }\n};")},
  { title:"Balanced Binary Tree", difficulty:"Easy", description:"Determine if a binary tree is height-balanced.", snippets:s("function isBalanced(root){\n  \n}","def isBalanced(root):\n    pass","class Solution{\n  public boolean isBalanced(TreeNode root){\n  }\n}","class Solution{\npublic:\n  bool isBalanced(TreeNode* root){\n  }\n};")},
  { title:"Symmetric Tree", difficulty:"Easy", description:"Check whether a binary tree is a mirror of itself.", snippets:s("function isSymmetric(root){\n  \n}","def isSymmetric(root):\n    pass","class Solution{\n  public boolean isSymmetric(TreeNode root){\n  }\n}","class Solution{\npublic:\n  bool isSymmetric(TreeNode* root){\n  }\n};")},
  { title:"Path Sum", difficulty:"Easy", description:"Determine if the tree has a root-to-leaf path summing to targetSum.", snippets:s("function hasPathSum(root,target){\n  \n}","def hasPathSum(root,target):\n    pass","class Solution{\n  public boolean hasPathSum(TreeNode root,int t){\n  }\n}","class Solution{\npublic:\n  bool hasPathSum(TreeNode* root,int t){\n  }\n};")},
  { title:"Diameter of Binary Tree", difficulty:"Easy", description:"Find the length of the longest path between any two nodes in a tree.", snippets:s("function diameterOfBinaryTree(root){\n  \n}","def diameterOfBinaryTree(root):\n    pass","class Solution{\n  public int diameterOfBinaryTree(TreeNode root){\n  }\n}","class Solution{\npublic:\n  int diameterOfBinaryTree(TreeNode* root){\n  }\n};")},
  { title:"Invert Binary Tree", difficulty:"Easy", description:"Invert a binary tree (flip left and right children recursively).", snippets:s("function invertTree(root){\n  \n}","def invertTree(root):\n    pass","class Solution{\n  public TreeNode invertTree(TreeNode root){\n  }\n}","class Solution{\npublic:\n  TreeNode* invertTree(TreeNode* root){\n  }\n};")},
  { title:"Min Stack", difficulty:"Medium", description:"Design a stack that supports push, pop, top, and getMin in O(1).", snippets:s("class MinStack{\n  push(val){}\n  pop(){}\n  top(){}\n  getMin(){}\n}","class MinStack:\n  def push(self,v):pass\n  def pop(self):pass\n  def top(self):pass\n  def getMin(self):pass","class MinStack{\n  public void push(int v){}\n  public void pop(){}\n  public int top(){}\n  public int getMin(){}\n}","class MinStack{\npublic:\n  void push(int v){}\n  void pop(){}\n  int top(){}\n  int getMin(){}\n};")},
  { title:"Implement Stack using Queues", difficulty:"Easy", description:"Implement a LIFO stack using only two queues.", snippets:s("class MyStack{\n  push(x){}\n  pop(){}\n  top(){}\n  empty(){}\n}","class MyStack:\n  def push(self,x):pass\n  def pop(self):pass\n  def top(self):pass\n  def empty(self):pass","class MyStack{\n  public void push(int x){}\n  public int pop(){}\n  public int top(){}\n  public boolean empty(){}\n}","class MyStack{\npublic:\n  void push(int x){}\n  int pop(){}\n  int top(){}\n  bool empty(){}\n};")},
  { title:"Implement Queue using Stacks", difficulty:"Easy", description:"Implement a FIFO queue using only two stacks.", snippets:s("class MyQueue{\n  push(x){}\n  pop(){}\n  peek(){}\n  empty(){}\n}","class MyQueue:\n  def push(self,x):pass\n  def pop(self):pass\n  def peek(self):pass\n  def empty(self):pass","class MyQueue{\n  public void push(int x){}\n  public int pop(){}\n  public int peek(){}\n  public boolean empty(){}\n}","class MyQueue{\npublic:\n  void push(int x){}\n  int pop(){}\n  int peek(){}\n  bool empty(){}\n};")},
  { title:"Nth Digit", difficulty:"Medium", description:"Find the nth digit of the infinite sequence 1,2,3,...,n.", snippets:s("function findNthDigit(n){\n  \n}","def findNthDigit(n):\n    pass","class Solution{\n  public int findNthDigit(int n){\n  }\n}","class Solution{\npublic:\n  int findNthDigit(int n){\n  }\n};")},
  { title:"Ugly Number II", difficulty:"Medium", description:"Find the nth ugly number (which has only prime factors 2, 3, 5).", snippets:s("function nthUglyNumber(n){\n  \n}","def nthUglyNumber(n):\n    pass","class Solution{\n  public int nthUglyNumber(int n){\n  }\n}","class Solution{\npublic:\n  int nthUglyNumber(int n){\n  }\n};")},
  { title:"Binary Watch", difficulty:"Easy", description:"Return all possible times a binary watch can display.", snippets:s("function readBinaryWatch(num){\n  \n}","def readBinaryWatch(num):\n    pass","class Solution{\n  public List<String> readBinaryWatch(int num){\n  }\n}","class Solution{\npublic:\n  vector<string> readBinaryWatch(int num){\n  }\n};")},
  { title:"Guess Number Higher or Lower", difficulty:"Easy", description:"Guess a number using a binary search with a provided guess API.", snippets:s("function guessNumber(n){\n  // guess(num) API returns -1, 0 or 1\n}","def guessNumber(n):\n    pass","class Solution{\n  public int guessNumber(int n){\n  }\n}","class Solution{\npublic:\n  int guessNumber(int n){\n  }\n};")},
  { title:"Sum of Left Leaves", difficulty:"Easy", description:"Find the sum of all left leaves in a binary tree.", snippets:s("function sumOfLeftLeaves(root){\n  \n}","def sumOfLeftLeaves(root):\n    pass","class Solution{\n  public int sumOfLeftLeaves(TreeNode root){\n  }\n}","class Solution{\npublic:\n  int sumOfLeftLeaves(TreeNode* root){\n  }\n};")},
  { title:"Largest Number", difficulty:"Medium", description:"Arrange numbers from array to form the largest number possible.", snippets:s("function largestNumber(nums){\n  \n}","def largestNumber(nums):\n    pass","class Solution{\n  public String largestNumber(int[] nums){\n  }\n}","class Solution{\npublic:\n  string largestNumber(vector<int>&nums){\n  }\n};")},
  { title:"Minimum Depth of Binary Tree", difficulty:"Easy", description:"Find the minimum depth (distance to nearest leaf) of a binary tree.", snippets:s("function minDepth(root){\n  \n}","def minDepth(root):\n    pass","class Solution{\n  public int minDepth(TreeNode root){\n  }\n}","class Solution{\npublic:\n  int minDepth(TreeNode* root){\n  }\n};")},
  { title:"Contains Duplicate", difficulty:"Easy", description:"Return true if any value appears at least twice in the array.", snippets:s("function containsDuplicate(nums){\n  \n}","def containsDuplicate(nums):\n    pass","class Solution{\n  public boolean containsDuplicate(int[] nums){\n  }\n}","class Solution{\npublic:\n  bool containsDuplicate(vector<int>&nums){\n  }\n};")},
  { title:"Prison Cells After N Days", difficulty:"Medium", description:"Return the state of prison cells after N days of cellular automaton.", snippets:s("function prisonAfterNDays(cells,n){\n  \n}","def prisonAfterNDays(cells,n):\n    pass","class Solution{\n  public int[] prisonAfterNDays(int[] cells,int n){\n  }\n}","class Solution{\npublic:\n  vector<int> prisonAfterNDays(vector<int>&cells,int n){\n  }\n};")},
  { title:"Number of Ways to Stay in the Same Place After Some Steps", difficulty:"Hard", description:"Count ways to return to index 0 after exactly steps steps on an array.", snippets:s("function numWays(steps,arrLen){\n  \n}","def numWays(steps,arrLen):\n    pass","class Solution{\n  public int numWays(int steps,int arrLen){\n  }\n}","class Solution{\npublic:\n  int numWays(int steps,int arrLen){\n  }\n};")},
  { title:"Leaf-Similar Trees", difficulty:"Easy", description:"Two binary trees are leaf-similar if their leaf value sequence is the same.", snippets:s("function leafSimilar(root1,root2){\n  \n}","def leafSimilar(root1,root2):\n    pass","class Solution{\n  public boolean leafSimilar(TreeNode root1,TreeNode root2){\n  }\n}","class Solution{\npublic:\n  bool leafSimilar(TreeNode* root1,TreeNode* root2){\n  }\n};")},
].map(q => ({...q, company: 'other'}));

const seedOther = async () => {
  try {
    await Question.deleteMany({ company: 'other' });
    await Question.insertMany(other);
    console.log(`Seeded ${other.length} questions in 'Other' category!`);
    process.exit(0);
  } catch (err) {
    console.error('Seed Error:', err);
    process.exit(1);
  }
};

seedOther();
